name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2

      - name: Configure Project
        run: cmake --preset default

      - name: Package Project
        run: cpack --preset default

      - name: Upload Project
        uses: actions/upload-artifact@v4.5.0
        with:
          path: build/*.tar.gz
          if-no-files-found: error
          overwrite: true
