name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.0

      - name: Configure Project
        uses: threeal/cmake-action@v2.0.0
        with:
          run-build: false

      - name: Install Project
        run: cmake --install build --prefix install

      - name: Upload Project
        uses: actions/upload-artifact@v4.4.0
        with:
          name: Assertion
          path: install
          if-no-files-found: error
          overwrite: true
