name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Configure Project
        uses: threeal/cmake-action@v2.0.0
        with:
          run-build: false

      - name: Install Project
        run: cmake --install build --prefix install

      - name: Upload Project as Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          path: install
