name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: ["**"]
jobs:
  deploy-pages:
    name: Deploy Pages
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    concurrency:
      group: pages
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Copy Modules
        run: |
          mkdir -p build/page
          git checkout main
          cp cmake/Assertion.cmake build/page/main
          for tag in $(git tag); do
            git checkout $tag
            cp cmake/Assertion.cmake build/page/$tag
          done

      - name: Upload Documentation
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: build/page

      - name: Deploy Pages
        id: deploy-pages
        uses: actions/deploy-pages@v4.0.5
