name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  test-project:
    name: Test Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Configure Project
        uses: threeal/cmake-action@v1.3.0
        with:
          options: BUILD_TESTING=ON

      - name: Test Project
        uses: threeal/ctest-action@v1.0.0
