name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  test-project:
    name: Test Project
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Configure Project
        uses: threeal/cmake-action@v2.0.0
        with:
          options: ASSERTION_ENABLE_TESTS=ON
          run-build: false

      - name: Test Project
        uses: threeal/ctest-action@v1.1.0
        with:
          verbose: true
